version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: cinema-mysql
    environment:
      MYSQL_ROOT_PASSWORD: jassi
      MYSQL_DATABASE: cinema_booking
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: cinema_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinema-network
    restart: unless-stopped

  # Backend Spring Boot Application
  backend:
    build: ./backend
    container_name: cinema-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cinema_booking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: cinema_user
      SPRING_DATASOURCE_PASSWORD: cinema_pass
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - cinema-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/cinemas"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Application
  frontend:
    build: ./frontendd
    container_name: cinema-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cinema-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  cinema-network:
    driver: bridge

