server:
  port: ${PORT:8080}

spring:
  application:
    name: cinema-booking-system
  
  datasource:
    url: ${DATABASE_URL}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

logging:
  level:
    com.cinema: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://your-frontend-url.railway.app}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true